# Generated by Django 4.2.11 on 2024-09-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
