# Generated by Django 4.2.11 on 2024-09-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='currentBalance',
            field=models.FloatField(default=0),
        ),
    ]
